window.leagueMap = {
// Premier League
"Bournemouth": "Premier League",
"Arsenal": "Premier League",
"Aston Villa": "Premier League",
"Brentford": "Premier League",
"Brighton": "Premier League",
"Burnley": "Premier League",
"Chelsea": "Premier League",
"Crystal Palace": "Premier League",
"Everton": "Premier League",
"Fulham": "Premier League",
"Leeds United": "Premier League",
"Liverpool": "Premier League",
"Manchester City": "Premier League",
"Manchester United": "Premier League",
"Newcastle United": "Premier League",
"Nottingham Forest": "Premier League",
"Sunderland": "Premier League",
"Tottenham Hotspur": "Premier League",
"West Ham United": "Premier League",
"Wolves": "Premier League",

// Scottish Premiership
"Aberdeen": "Scottish Premiership",
"Celtic": "Scottish Premiership",
"Dundee": "Scottish Premiership",
"Dundee United": "Scottish Premiership",
"Falkirk": "Scottish Premiership",
"Heart of Midlothian": "Scottish Premiership",
"Hibernian": "Scottish Premiership",
"Kilmarnock": "Scottish Premiership",
"Livingston": "Scottish Premiership",
"Motherwell": "Scottish Premiership",
"Rangers": "Scottish Premiership",
"St Mirren": "Scottish Premiership",

// Championship
"Birmingham City": "Championship",
"Blackburn Rovers": "Championship",
"Bristol City": "Championship",
"Charlton Athletic": "Championship",
"Coventry City": "Championship",
"Derby County": "Championship",
"Hull City": "Championship",
"Ipswich Town": "Championship",
"Leicester City": "Championship",
"Middlesbrough": "Championship",
"Millwall": "Championship",
"Norwich City": "Championship",
"Oxford United": "Championship",
"Portsmouth": "Championship",
"Preston North End": "Championship",
"Queens Park Rangers": "Championship",
"Sheffield United": "Championship",
"Sheffield Wednesday": "Championship",
"Southampton": "Championship",
"Stoke City": "Championship",
"Swansea City": "Championship",
"Watford": "Championship",
"West Bromwich Albion": "Championship",
"Wrexham": "Championship",

// English League One
"AFC Wimbledon": "English League One",
"Barnsley": "English League One",
"Blackpool": "English League One",
"Bolton Wanderers": "English League One",
"Bradford City": "English League One",
"Burton Albion": "English League One",
"Cardiff City": "English League One",
"Doncaster Rovers": "English League One",
"Exeter City": "English League One",
"Huddersfield Town": "English League One",
"Leyton Orient": "English League One",
"Lincoln City": "English League One",
"Luton Town": "English League One",
"Mansfield Town": "English League One",
"Northampton Town": "English League One",
"Peterborough United": "English League One",
"Plymouth Argyle": "English League One",
"Port Vale": "English League One",
"Reading": "English League One",
"Rotherham United": "English League One",
"Stevenage": "English League One",
"Stockport County": "English League One",
"Wigan Athletic": "English League One",
"Wycombe Wanderers": "English League One",

// English League Two
"Accrington Stanley": "English League Two",
"Barnet": "English League Two",
"Barrow": "English League Two",
"Bristol Rovers": "English League Two",
"Bromley": "English League Two",
"Cambridge United": "English League Two",
"Cheltenham Town": "English League Two",
"Chesterfield": "English League Two",
"Colchester United": "English League Two",
"Crawley Town": "English League Two",
"Crewe Alexandra": "English League Two",
"Fleetwood Town": "English League Two",
"Gillingham": "English League Two",
"Grimsby Town": "English League Two",
"Harrogate Town": "English League Two",
"MK Dons": "English League Two",
"Newport County": "English League Two",
"Notts County": "English League Two",
"Oldham Athletic": "English League Two",
"Salford City": "English League Two",
"Shrewsbury Town": "English League Two",
"Swindon Town": "English League Two",
"Tranmere Rovers": "English League Two",
"Walsall": "English League Two",

// La Liga
"Alaves": "La Liga",
"Athletic Club": "La Liga",
"Atletico Madrid": "La Liga",
"Barcelona": "La Liga",
"Celta Vigo": "La Liga",
"Elche": "La Liga",
"Espanyol": "La Liga",
"Getafe": "La Liga",
"Girona": "La Liga",
"Mallorca": "La Liga",
"Osasuna": "La Liga",
"Rayo Vallecano": "La Liga",
"Real Betis": "La Liga",
"Real Madrid": "La Liga",
"Real Oviedo": "La Liga",
"Real Sociedad": "La Liga",
"Sevilla": "La Liga",
"Valencia": "La Liga",
"Villarreal": "La Liga",

// Ligue 1
"Angers": "Ligue 1",
"Auxerre": "Ligue 1",
"Brest": "Ligue 1",
"Le Havre": "Ligue 1",
"Lens": "Ligue 1",
"Lille": "Ligue 1",
"Lorient": "Ligue 1",
"Lyon": "Ligue 1",
"Marseille": "Ligue 1",
"Metz": "Ligue 1",
"Monaco": "Ligue 1",
"Nantes": "Ligue 1",
"Nice": "Ligue 1",
"Paris FC": "Ligue 1",
"PSG": "Ligue 1",
"Rennes": "Ligue 1",
"Strasbourg": "Ligue 1",
"Toulouse": "Ligue 1",

// MLS
"Atlanta United FC": "MLS",
"Austin FC": "MLS",
"CF Montréal": "MLS",
"Charlotte FC": "MLS",
"Chicago Fire FC": "MLS",
"Colorado Rapids": "MLS",
"Columbus Crew": "MLS",
"D.C. United": "MLS",
"FC Cincinnati": "MLS",
"FC Dallas": "MLS",
"Houston Dynamo FC": "MLS",
"Inter Miami CF": "MLS",
"LA Galaxy": "MLS",
"Los Angeles FC": "MLS",
"Minnesota United FC": "MLS",
"Montreal Impact": "MLS",
"Nashville SC": "MLS",
"New England Revolution": "MLS",
"New York City FC": "MLS",
"New York Red Bulls": "MLS",
"Orlando City SC": "MLS",
"Philadelphia Union": "MLS",
"Phoenix Rising": "USL",
"Portland Timbers": "MLS",
"Real Salt Lake": "MLS",
"San Diego FC": "MLS",
"San Jose Earthquakes": "MLS",
"Seattle Sounders FC": "MLS",
"Sporting Kansas City": "MLS",
"St. Louis City SC": "MLS",
"Toronto FC": "MLS",
"Vancouver Whitecaps FC": "MLS",

// Primeira Liga
"Alverca": "Primeira Liga",
"Arouca": "Primeira Liga",
"AVS": "Primeira Liga",
"Benfica": "Primeira Liga",
"Braga": "Primeira Liga",
"Casa Pia": "Primeira Liga",
"Estoril Praia": "Primeira Liga",
"Estrela da Amadora": "Primeira Liga",
"Famalicao": "Primeira Liga",
"Gil Vicente": "Primeira Liga",
"Moreirense": "Primeira Liga",
"Nacional": "Primeira Liga",
"Porto": "Primeira Liga",
"Rio Ave": "Primeira Liga",
"Santa Clara": "Primeira Liga",
"Sporting CP": "Primeira Liga",
"Tondela": "Primeira Liga",
"Vitoria de Guimaraes": "Primeira Liga",

// Serie A
"AC Milan": "Serie A",
"Atalanta": "Serie A",
"Bologna": "Serie A",
"Cagliari": "Serie A",
"Como": "Serie A",
"Cremonese": "Serie A",
"Fiorentina": "Serie A",
"Genoa": "Serie A",
"Hellas Verona": "Serie A",
"Inter Milan": "Serie A",
"Juventus": "Serie A",
"Lazio": "Serie A",
"Lecce": "Serie A",
"Napoli": "Serie A",
"Parma": "Serie A",
"Pisa": "Serie A",
"Roma": "Serie A",
"Sassuolo": "Serie A",
"Torino": "Serie A",
"Udinese": "Serie A",

// Saudi Pro League
"Al Ahli": "Saudi Pro League",
"Al Ettifaq": "Saudi Pro League",
"Al Fateh": "Saudi Pro League",
"Al Fayha": "Saudi Pro League",
"Al Hazem": "Saudi Pro League",
"Al Hilal": "Saudi Pro League",
"Al Ittihad": "Saudi Pro League",
"Al Khaleej": "Saudi Pro League",
"Al Kholood": "Saudi Pro League",
"Al Najma": "Saudi Pro League",
"Al Nassr": "Saudi Pro League",
"Al Okhdood": "Saudi Pro League",
"Al Qadsiah": "Saudi Pro League",
"Al Riyadh": "Saudi Pro League",
"Al Shabab": "Saudi Pro League",
"Al Taawoun": "Saudi Pro League",
"Damac": "Saudi Pro League",
"Neom": "Saudi Pro League",

// Brasileirão
"Athletico Paranaense": "Brasileirão",
"Atletico Mineiro": "Brasileirão",
"Bahia": "Brasileirão",
"Botafogo": "Brasileirão",
"Chapecoense": "Brasileirão",
"Corinthians": "Brasileirão",
"Coritiba": "Brasileirão",
"Cruzeiro": "Brasileirão",
"Flamengo": "Brasileirão",
"Fluminense": "Brasileirão",
"Gremio": "Brasileirão",
"Internacional": "Brasileirão",
"Mirassol": "Brasileirão",
"Palmeiras": "Brasileirão",
"Red Bull Bragantino": "Brasileirão",
"Remo": "Brasileirão",
"Santos": "Brasileirão",
"Sao Paulo": "Brasileirão",
"Vasco da Gama": "Brasileirão",
"Vitoria": "Brasileirão",

// Eliteserien
"Aalesund": "Eliteserien",
"Bodo/Glimt": "Eliteserien",
"Brann": "Eliteserien",
"Fredrikstad": "Eliteserien",
"HamKam": "Eliteserien",
"KFUM": "Eliteserien",
"Kristiansund": "Eliteserien",
"Lillestrøm": "Eliteserien",
"Molde": "Eliteserien",
"Rosenborg": "Eliteserien",
"Sandefjord": "Eliteserien",
"Sarpsborg": "Eliteserien",
"Start": "Eliteserien",
"Tromso": "Eliteserien",
"Viking": "Eliteserien",
"Vålerenga": "Eliteserien",

// Austria Bundesliga
"Austria Wien": "Austria Bundesliga",
"Blau-Weiss Linz": "Austria Bundesliga",
"Grazer AK": "Austria Bundesliga",
"LASK": "Austria Bundesliga",
"Rapid Wien": "Austria Bundesliga",
"Red Bull Salzburg": "Austria Bundesliga",
"Rheindorf Altach": "Austria Bundesliga",
"Ried": "Austria Bundesliga",
"Sturm Graz": "Austria Bundesliga",
"TSV Hartberg": "Austria Bundesliga",
"Wolfsberger AC": "Austria Bundesliga",
"WSG Tirol": "Austria Bundesliga",

// Bundesliga
"1. FC Heidenheim": "Bundesliga",
"1. FC Koln": "Bundesliga",
"Bayer Leverkusen": "Bundesliga",
"Bayern Munich": "Bundesliga",
"Borussia Dortmund": "Bundesliga",
"Borussia Monchengladbach": "Bundesliga",
"Eintracht Frankfurt": "Bundesliga",
"FC Augsburg": "Bundesliga",
"FC St. Pauli": "Bundesliga",
"Hamburg": "Bundesliga",
"Mainz 05": "Bundesliga",
"RB Leipzig": "Bundesliga",
"SC Freiburg": "Bundesliga",
"TSG Hoffenheim": "Bundesliga",
"Union Berlin": "Bundesliga",
"VfB Stuttgart": "Bundesliga",
"VfL Wolfsburg": "Bundesliga",
"Werder Bremen": "Bundesliga",

// Liga MX
"America": "Liga MX",
"Atletico San Luis": "Liga MX",
"Atlas": "Liga MX",
"Cruz Azul": "Liga MX",
"Guadalajara": "Liga MX",
"Juarez": "Liga MX",
"Leon": "Liga MX",
"Mazatlan": "Liga MX",
"Monterrey": "Liga MX",
"Necaxa": "Liga MX",
"Pachuca": "Liga MX",
"Puebla": "Liga MX",
"Queretaro": "Liga MX",
"Santos Laguna": "Liga MX",
"Tijuana": "Liga MX",
"Toluca": "Liga MX",
"UANL": "Liga MX",
"UNAM": "Liga MX",

// J1 League
"Avispa Fukuoka": "J1 League",
"Cerezo Osaka": "J1 League",
"Fagiano Okayama": "J1 League",
"FC Tokyo": "J1 League",
"Gamba Osaka": "J1 League",
"JEF United Chiba": "J1 League",
"Kashima Antlers": "J1 League",
"Kashiwa Reysol": "J1 League",
"Kawasaki Frontale": "J1 League",
"Kyoto Sanga": "J1 League",
"Machida Zelvia": "J1 League",
"Mito HollyHock": "J1 League",
"Nago ya Grampus": "J1 League",
"Sanfrecce Hiroshima": "J1 League",
"Shimizu S-Pulse": "J1 League",
"Tokyo Verdy": "J1 League",
"Urawa Red Diamonds": "J1 League",
"V-Varen Nagasaki": "J1 League",
"Vissel Kobe": "J1 League",
"Yokohama F. Marinos": "J1 League",

// UAE Pro League
"Ajman": "UAE Pro League",
"Al Ain": "UAE Pro League",
"Al Bataeh": "UAE Pro League",
"Al Dhafra": "UAE Pro League",
"Al Jazira": "UAE Pro League",
"Al Nasr": "UAE Pro League",
"Al Wahda": "UAE Pro League",
"Al Wasl": "UAE Pro League",
"Baniyas": "UAE Pro League",
"Dibba": "UAE Pro League",
"Kalba": "UAE Pro League",
"Khor Fakkan": "UAE Pro League",
"Shabab Al Ahli": "UAE Pro League",
"Sharjah": "UAE Pro League",

// Qatar Stars League
"Al Arabi": "Qatar Stars League",
"Al Duhail": "Qatar Stars League",
"Al Gharafa": "Qatar Stars League",
"Al Rayyan": "Qatar Stars League",
"Al Sadd": "Qatar Stars League",
"Al Sailiya": "Qatar Stars League",
"Al Shahaniya": "Qatar Stars League",
"Al Shamal": "Qatar Stars League",
"Al Wakrah": "Qatar Stars League",
"Qatar SC": "Qatar Stars League",
"Umm Salal": "Qatar Stars League",

// HNL
"Dinamo Zagreb": "HNL",
"Gorica": "HNL",
"Hajduk Split": "HNL",
"Istra 1961": "HNL",
"Lokomotiva": "HNL",
"Osijek": "HNL",
"Rijeka": "HNL",
"Slaven Belupo": "HNL",
"Varazdin": "HNL",
"Vukovar 1991": "HNL",

// Premier Liga BiH
"Borac": "Premier Liga BiH",
"Posusje": "Premier Liga BiH",
"Radnik": "Premier Liga BiH",
"Rudar": "Premier Liga BiH",
"Sarajevo": "Premier Liga BiH",
"Sloga": "Premier Liga BiH",
"Siroki Brijeg": "Premier Liga BiH",
"Velez": "Premier Liga BiH",
"Zeljeznicar": "Premier Liga BiH",
"Zrinjski": "Premier Liga BiH",

// Ekstraklasa
"Arka Gdynia": "Ekstraklasa",
"Bruk-Bet Termalica Nieciecza": "Ekstraklasa",
"Cracovia": "Ekstraklasa",
"GKS Katowice": "Ekstraklasa",
"Gornik Zabrze": "Ekstraklasa",
"Jagiellonia Bialystok": "Ekstraklasa",
"Korona Kielce": "Ekstraklasa",
"Lech Poznan": "Ekstraklasa",
"Lechia Gdansk": "Ekstraklasa",
"Legia Warsaw": "Ekstraklasa",
"Motor Lublin": "Ekstraklasa",
"Piast Gliwice": "Ekstraklasa",
"Pogon Szczecin": "Ekstraklasa",
"Radomiak Radom": "Ekstraklasa",
"Rakow Czestochowa": "Ekstraklasa",
"Widzew Lodz": "Ekstraklasa",
"Wisla Plock": "Ekstraklasa",
"Zaglebie Lubin": "Ekstraklasa",

// Liga AUF Uruguaya
"Albion": "Liga AUF Uruguaya",
"Boston River": "Liga AUF Uruguaya",
"Central Espanol": "Liga AUF Uruguaya",
"Cerro": "Liga AUF Uruguaya",
"Cerro Largo": "Liga AUF Uruguaya",
"Danubio": "Liga AUF Uruguaya",
"Defensor Sporting": "Liga AUF Uruguaya",
"Deportivo Maldonado": "Liga AUF Uruguaya",
"Juventud": "Liga AUF Uruguaya",
"Montevideo City Torque": "Liga AUF Uruguaya",
"Montevideo Wanderers": "Liga AUF Uruguaya",
"Nacional": "Liga AUF Uruguaya",
"Penarol": "Liga AUF Uruguaya",
"Progreso": "Liga AUF Uruguaya",
"Racing": "Liga AUF Uruguaya",

// Eredivisie
"ADO Den Haag": "Eredivisie",
"Ajax": "Eredivisie",
"AZ": "Eredivisie",
"Excelsior": "Eredivisie",
"FC Groningen": "Eredivisie",
"FC Twente": "Eredivisie",
"FC Utrecht": "Eredivisie",
"Feyenoord": "Eredivisie",
"Fortuna Sittard": "Eredivisie",
"Go Ahead Eagles": "Eredivisie",
"NEC": "Eredivisie",
"PEC Zwolle": "Eredivisie",
"PSV": "Eredivisie",
"SC Cambuur": "Eredivisie",
"SC Heerenveen": "Eredivisie",
"Sparta Rotterdam": "Eredivisie",
"Volendam": "Eredivisie",

// Egyptian Premier League
"Al Ahly": "Egyptian Premier League",
"Al Masry": "Egyptian Premier League",
"Al Mokawloon Al Arab": "Egyptian Premier League",
"Ceramica Cleopatra": "Egyptian Premier League",
"ENPPI": "Egyptian Premier League",
"El Gouna": "Egyptian Premier League",
"Ghazl El Mahalla": "Egyptian Premier League",
"Haras El Hodoud": "Egyptian Premier League",
"Ismaily": "Egyptian Premier League",
"Kahraba Ismailia SC": "Egyptian Premier League",
"Modern Sport": "Egyptian Premier League",
"National Bank of Egypt": "Egyptian Premier League",
"Petrojet": "Egyptian Premier League",
"Pharco": "Egyptian Premier League",
"Pyramids": "Egyptian Premier League",
"Smouha": "Egyptian Premier League",
"Tala'ea El Gaish": "Egyptian Premier League",
"Wadi Degla": "Egyptian Premier League",
"ZED": "Egyptian Premier League",
"Zamalek": "Egyptian Premier League",

// Swiss Super League
"Basel": "Swiss Super League",
"Grasshopper": "Swiss Super League",
"Lausanne Sport": "Swiss Super League",
"Lugano": "Swiss Super League",
"Luzern": "Swiss Super League",
"Servette": "Swiss Super League",
"Sion": "Swiss Super League",
"St Gallen": "Swiss Super League",
"Thun": "Swiss Super League",
"Winterthur": "Swiss Super League",
"Young Boys": "Swiss Super League",
"Zurich": "Swiss Super League",

// Ligue 2
"Amiens": "Ligue 2",
"Annecy": "Ligue 2",
"Bastia": "Ligue 2",
"Boulogne": "Ligue 2",
"Clermont": "Ligue 2",
"Dunkerque": "Ligue 2",
"Grenoble": "Ligue 2",
"Guingamp": "Ligue 2",
"Laval": "Ligue 2",
"Le Mans": "Ligue 2",
"Montpellier": "Ligue 2",
"Nancy": "Ligue 2",
"Pau": "Ligue 2",
"Red Star": "Ligue 2",
"Reims": "Ligue 2",
"Rodez": "Ligue 2",
"Saint Etienne": "Ligue 2",
"Troyes": "Ligue 2",

// Belgian Pro League
"Anderlecht": "Belgian Pro League",
"Antwerp": "Belgian Pro League",
"Beveren": "Belgian Pro League",
"Cercle Brugge": "Belgian Pro League",
"Charleroi": "Belgian Pro League",
"Club Brugge": "Belgian Pro League",
"Genk": "Belgian Pro League",
"Gent": "Belgian Pro League",
"Kortrijk": "Belgian Pro League",
"La Louviere": "Belgian Pro League",
"Mechelen": "Belgian Pro League",
"OH Leuven": "Belgian Pro League",
"Sint-Truiden": "Belgian Pro League",
"Standard Liege": "Belgian Pro League",
"Union SG": "Belgian Pro League",
"Westerlo": "Belgian Pro League",
"Zulte Waregem": "Belgian Pro League",

// Chinese Super League
"Beijing Guoan": "Chinese Super League",
"Chengdu Rongcheng": "Chinese Super League",
"Chongqing Tonglianglong": "Chinese Super League",
"Dalian Yingbo": "Chinese Super League",
"Henan": "Chinese Super League",
"Liaoning Tieren": "Chinese Super League",
"Qingdao Hainiu": "Chinese Super League",
"Qingdao West Coast": "Chinese Super League",
"Shanghai Port": "Chinese Super League",
"Shanghai Shenhua": "Chinese Super League",
"Shandong Taishan": "Chinese Super League",
"Shenzhen Peng City": "Chinese Super League",
"Tianjin Jinmen Tiger": "Chinese Super League",
"Wuhan Three Towns": "Chinese Super League",
"Yunnan Yukun": "Chinese Super League",
"Zhejiang": "Chinese Super League",

// Segunda División
"Albacete": "Segunda División",
"Almeria": "Segunda División",
"Andorra": "Segunda División",
"Burgos": "Segunda División",
"Cadiz": "Segunda División",
"Castellon": "Segunda División",
"Ceuta": "Segunda División",
"Cordoba": "Segunda División",
"Cultural Leonesa": "Segunda División",
"Deportivo La Coruna": "Segunda División",
"Eibar": "Segunda División",
"Granada": "Segunda División",
"Huesca": "Segunda División",
"Las Palmas": "Segunda División",
"Leganes": "Segunda División",
"Malaga": "Segunda División",
"Mirandes": "Segunda División",
"Racing Santander": "Segunda División",
"Real Sociedad B": "Segunda División",
"San Sebastian": "Segunda División",
"Sporting Gijon": "Segunda División",
"Valladolid": "Segunda División",
"Vitoria-Gasteiz": "Segunda División",
"Zaragoza": "Segunda División",

// Ukrainian Premier League
"Dynamo Kyiv": "Ukrainian Premier League",
"Epitsentr Kamianets-Podilskyi": "Ukrainian Premier League",
"FC Kudrivka": "Ukrainian Premier League",
"Karpaty Lviv": "Ukrainian Premier League",
"Kolos Kovalivka": "Ukrainian Premier League",
"Kryvbas Kryvyi Rih": "Ukrainian Premier League",
"LNZ Cherkasy": "Ukrainian Premier League",
"Metalist 1925 Kharkiv": "Ukrainian Premier League",
"Obolon Kyiv": "Ukrainian Premier League",
"Oleksandriya": "Ukrainian Premier League",
"Polissya Zhytomyr": "Ukrainian Premier League",
"Rukh Lviv": "Ukrainian Premier League",
"SC Poltava": "Ukrainian Premier League",
"Shakhtar Donetsk": "Ukrainian Premier League",
"Veres Rivne": "Ukrainian Premier League",
"Zorya Luhansk": "Ukrainian Premier League",

// Russian Premier League
"Akhmat": "Russian Premier League",
"Akron": "Russian Premier League",
"Anzhi Makhachkala": "Russian Premier League",
"Baltika": "Russian Premier League",
"CSKA Moscow": "Russian Premier League",
"Dynamo Moscow": "Russian Premier League",
"Krasnodar": "Russian Premier League",
"Krylia Sovetov": "Russian Premier League",
"Lokomotiv Moscow": "Russian Premier League",
"Orenburg": "Russian Premier League",
"Pari": "Russian Premier League",
"Rostov": "Russian Premier League",
"Rubin Kazan": "Russian Premier League",
"Sochi": "Russian Premier League",
"Spartak": "Russian Premier League",
"Zenit": "Russian Premier League",

// Turkish Super Lig
"Alanyaspor": "Turkish Super Lig",
"Antalyaspor": "Turkish Super Lig",
"Basaksehir": "Turkish Super Lig",
"Besiktas": "Turkish Super Lig",
"Eyupspor": "Turkish Super Lig",
"Fatih Karagumruk": "Turkish Super Lig",
"Fenerbahce": "Turkish Super Lig",
"Galatasaray": "Turkish Super Lig",
"Gaziantep": "Turkish Super Lig",
"Genclerbirligi": "Turkish Super Lig",
"Goztepe": "Turkish Super Lig",
"Kasimpasa": "Turkish Super Lig",
"Kayserispor": "Turkish Super Lig",
"Kocaelispor": "Turkish Super Lig",
"Konyaspor": "Turkish Super Lig",
"Rizespor": "Turkish Super Lig",
"Samsunspor": "Turkish Super Lig",
"Trabzonspor": "Turkish Super Lig",

// Greek Super League
"AE Kifisia": "Greek Super League",
"AEK Athens": "Greek Super League",
"AEL": "Greek Super League",
"Aris": "Greek Super League",
"Asteras Tripolis": "Greek Super League",
"Atromitos": "Greek Super League",
"Levadiakos": "Greek Super League",
"OFI": "Greek Super League",
"Olympiacos": "Greek Super League",
"PAOK": "Greek Super League",
"Panathinaikos": "Greek Super League",
"Panetolikos": "Greek Super League",
"Panserraikos": "Greek Super League",
"Volos": "Greek Super League",

// Uzbek Super League
"AGMK": "Uzbek Super League",
"Andijon": "Uzbek Super League",
"Bukhara": "Uzbek Super League",
"Bunyodkor": "Uzbek Super League",
"Dinamo": "Uzbek Super League",
"Khorazm": "Uzbek Super League",
"Kokand 1912": "Uzbek Super League",
"Lokomotiv": "Uzbek Super League",
"Mashal": "Uzbek Super League",
"Nasaf": "Uzbek Super League",
"Navbahor": "Uzbek Super League",
"Neftchi": "Uzbek Super League",
"Pakhtakor": "Uzbek Super League",
"Qizilqum": "Uzbek Super League",
"Sogdiana": "Uzbek Super League",
"Surkhon": "Uzbek Super League",

// Allsvenskan
"AIK": "Allsvenskan",
"BK Hacken": "Allsvenskan",
"Degerfors IF": "Allsvenskan",
"Djurgardens IF": "Allsvenskan",
"GAIS": "Allsvenskan",
"Halmstads BK": "Allsvenskan",
"Hammarby IF": "Allsvenskan",
"IF Brommapojkarna": "Allsvenskan",
"IF Elfsborg": "Allsvenskan",
"IFK Goteborg": "Allsvenskan",
"IK Sirius": "Allsvenskan",
"Kalmar FF": "Allsvenskan",
"Malmo FF": "Allsvenskan",
"Mjallby AIF": "Allsvenskan",
"Orgryte IS": "Allsvenskan",
"Vasteras SK": "Allsvenskan",

// A-League
"Adelaide United": "A-League",
"Auckland FC": "A-League",
"Brisbane Roar": "A-League",
"Central Coast Mariners": "A-League",
"Macarthur FC": "A-League",
"Melbourne City": "A-League",
"Melbourne Victory": "A-League",
"Newcastle Jets": "A-League",
"Perth Glory": "A-League",
"Sydney FC": "A-League",
"Wellington Phoenix": "A-League",
"Western Sydney Wanderers": "A-League",

// Argentine Primera División
"Aldosivi": "Argentine Primera División",
"Alfredo Terrera": "Argentine Primera División",
"Argentinos Juniors": "Argentine Primera División",
"Atletico Tucuman": "Argentine Primera División",
"Banfield": "Argentine Primera División",
"Barracas Central": "Argentine Primera División",
"Belgrano": "Argentine Primera División",
"Boca Juniors": "Argentine Primera División",
"Central Cordoba": "Argentine Primera División",
"Defensa y Justicia": "Argentine Primera División",
"Deportivo Riestra": "Argentine Primera División",
"Estudiantes": "Argentine Primera División",
"Gimnasia y Esgrima": "Argentine Primera División",
"Huracan": "Argentine Primera División",
"Independiente": "Argentine Primera División",
"Independiente Rivadavia": "Argentine Primera División",
"Instituto": "Argentine Primera División",
"Lanus": "Argentine Primera División",
"Newells Old Boys": "Argentine Primera División",
"Platense": "Argentine Primera División",
"Racing": "Argentine Primera División",
"River Plate": "Argentine Primera División",
"Rosario Central": "Argentine Primera División",
"San Lorenzo": "Argentine Primera División",
"Sarmiento": "Argentine Primera División",
"Talleres": "Argentine Primera División",
"Tigre": "Argentine Primera División",
"Union": "Argentine Primera División",
"Velez Sarsfield": "Argentine Primera División",

// Czech First League
"1. FC Slovacko": "Czech First League",
"Bohemians 1905": "Czech First League",
"FC Banik Ostrava": "Czech First League",
"FC Hradec Kralove": "Czech First League",
"FC Slovan Liberec": "Czech First League",
"FC Viktoria Plzen": "Czech First League",
"FC Zlin": "Czech First League",
"FK Dukla Prague": "Czech First League",
"FK Jablonec": "Czech First League",
"FK Mlada Boleslav": "Czech First League",
"FK Pardubice": "Czech First League",
"FK Teplice": "Czech First League",
"MFK Karvina": "Czech First League",
"SK Sigma Olomouc": "Czech First League",
"SK Slavia Prague": "Czech First League",
"Sparta Prague": "Czech First League",

// Slovenian PrvaLiga
"Aluminij": "Slovenian PrvaLiga",
"Bravo": "Slovenian PrvaLiga",
"Celje": "Slovenian PrvaLiga",
"Domzale": "Slovenian PrvaLiga",
"Koper": "Slovenian PrvaLiga",
"Maribor": "Slovenian PrvaLiga",
"Mura": "Slovenian PrvaLiga",
"Olimpija Ljubljana": "Slovenian PrvaLiga",
"Primorje": "Slovenian PrvaLiga",
"Radomlje": "Slovenian PrvaLiga",

// Serie B
"Avellino": "Serie B",
"Bari": "Serie B",
"Carrarese": "Serie B",
"Catanzaro": "Serie B",
"Cesena": "Serie B",
"Empoli": "Serie B",
"Frosinone": "Serie B",
"Juve Stabia": "Serie B",
"Mantova": "Serie B",
"Modena": "Serie B",
"Monza": "Serie B",
"Padova": "Serie B",
"Palermo": "Serie B",
"Pescara": "Serie B",
"Reggiana": "Serie B",
"Sampdoria": "Serie B",
"Spezia": "Serie B",
"Sudtirol": "Serie B",
"Venezia": "Serie B",
"Virtus Entella": "Serie B",

// Bundesliga 2
"1. FC Kaiserslautern": "Bundesliga 2",
"1. FC Magdeburg": "Bundesliga 2",
"1. FC Nurnberg": "Bundesliga 2",
"Arminia Bielefeld": "Bundesliga 2",
"Darmstadt 98": "Bundesliga 2",
"Dynamo Dresden": "Bundesliga 2",
"Eintracht Braunschweig": "Bundesliga 2",
"Fortuna Dusseldorf": "Bundesliga 2",
"Greuther Furth": "Bundesliga 2",
"Hannover 96": "Bundesliga 2",
"Hertha BSC": "Bundesliga 2",
"Holstein Kiel": "Bundesliga 2",
"Karlsruher SC": "Bundesliga 2",
"Preussen Munster": "Bundesliga 2",
"SC Paderborn": "Bundesliga 2",
"Schalke": "Bundesliga 2",
"SV Elversberg": "Bundesliga 2",
"VfL Bochum": "Bundesliga 2",

// Liga Portugal 2
"Academico de Viseu": "Liga Portugal 2",
"Benfica B": "Liga Portugal 2",
"Chaves": "Liga Portugal 2",
"Farense": "Liga Portugal 2",
"Feirense": "Liga Portugal 2",
"Felgueiras": "Liga Portugal 2",
"Leixoes": "Liga Portugal 2",
"Lusitania Lourosa": "Liga Portugal 2",
"Maritimo": "Liga Portugal 2",
"Oliveirense": "Liga Portugal 2",
"Pacos de Ferreira": "Liga Portugal 2",
"Penafiel": "Liga Portugal 2",
"Portimonense": "Liga Portugal 2",
"Porto B": "Liga Portugal 2",
"Sporting CP B": "Liga Portugal 2",
"Torreense": "Liga Portugal 2",
"Uniao de Leiria": "Liga Portugal 2",
"Vizela": "Liga Portugal 2",

// Slovak Super Liga
"DAC Dunajska Streda": "Slovak Super Liga",
"Komarno": "Slovak Super Liga",
"Kosice": "Slovak Super Liga",
"Podbrezova": "Slovak Super Liga",
"Ruzomberok": "Slovak Super Liga",
"Skalica": "Slovak Super Liga",
"Slovan Bratislava": "Slovak Super Liga",
"Spartak Trnava": "Slovak Super Liga",
"Tatran Presov": "Slovak Super Liga",
"Trencin": "Slovak Super Liga",
"Zemplin Michalovce": "Slovak Super Liga",
"Zilina": "Slovak Super Liga",

// Erovnuli Liga
"Dila Gori": "Erovnuli Liga",
"Dinamo Batumi": "Erovnuli Liga",
"Dinamo Tbilisi": "Erovnuli Liga",
"Gagra": "Erovnuli Liga",
"Iberia 1999": "Erovnuli Liga",
"Meshakhte": "Erovnuli Liga",
"Rustavi": "Erovnuli Liga",
"Samgurali Tsqaltubo": "Erovnuli Liga",
"Spaeri": "Erovnuli Liga",
"Torpedo Kutaisi": "Erovnuli Liga",

//Others
"Chennaiyin": "Indian Super League",
"Persib Bandung": "Indonesia Super League",
"Sabail": "Azerbaijan First League",
"AlbinoLeffe": "Serie C",
"IFK Hasselholm": "Swedish Division 2",
"Tampa Bay Rowdies": "USL Championship",
"Stromsgodset": "Eliteserien",
"AS Douanes": "Senegal Premier League",
"VVV Venlo": "Eerste Divisie",
"FC Jurong": "Singapore Premier League",
"Paro": "Bhutan Premier League",
"Suduva": "A Lyga",
"Neftci Baku": "Azerbaijan Premier League",
"Aktobe": "Kazakhstan Premier League",
"ADO Den Haag": "Eerste Divisie",
"Issia Wazi": "Ivorian Ligue 2",
"Los Angeles Aztecs": "North American Soccer League",
"Boston Minutemen": "North American Soccer League",
"New York Cosmos": "North American Soccer League",
"San Diego Sockers": "North American Soccer League",
"Toronto Metros-Croatia": "North American Soccer League",
"Las Vegas Quicksilvers" : "North American Soccer League",
"Fort Lauderdale Strikers": "North American Soccer League",
"Millonarios": "Categoría Primera A",
"Independiente Medellin": "Categoría Primera A",
"America de Cali": "Categoría Primera A",
"California Surf": "North American Soccer League",
"Carolina Lightnin'": "North American Soccer League",
"Colorado Caribous": "North American Soccer League",
"San Antonia Thunder": "North American Soccer League",
"Washington Diplomats": "North American Soccer League",
"St Polten": "Austrian Bundesliga 2",
"Pelita Jaya": "Indonesia Super League",
"PSIS Semarang": "Indonesia Super League",
"PSM Makassar": "Indonesia Super League",
"Partizan": "Serbian SuperLiga",
"Omonia": "Cypriot First Division",
"Apollon Limassol": "Cypriot First Division",
"Anorthosis Famagusta": "Cypriot First Division",
"Amanat Baghdad": "Iraq Stars League",
"Aguilas Doradas": "Categoría Primera A",
"Alianza Petrolera": "Categoría Primera A",
"Atletico Nacional": "Categoría Primera A",
"FC Liefering": "Austrian Bundesliga 2",
"Beerschot": "Belgian First Division B",
"Brussels": "Belgian First Division B",
"Club NXT": "Belgian First Division B",
"Colo-Colo": "Chilean Primera División",
"Universidad de Chile": "Chilean Primera División",
"Universidad Catolica": "Chilean Primera División",
"Willem II": "Eerste Divisie",
"Atlante": "Liga MX",
"FC Juarez": "Liga MX",
"FC Necaxa": "Liga MX",
"Cortulua": "Categoría Primera A",
"Deportes Tolima": "Categoría Primera A",
"Envigado": "Categoría Primera A",
"Dinamo Bucuresti": "Liga I",
"FCSB": "Liga I",
"Universitatea Craiova": "Liga I",
"Atletico Junior": "Categoría Primera A",
"America de Cali": "Categoría Primera A",
"Independiente Medellin": "Categoría Primera A",
"Millonarios": "Categoría Primera A",
"FC Nordsjaelland": "Danish Superliga",
"FC Midtjylland": "Danish Superliga",
"Brondby IF": "Danish Superliga",
"Pyunik": "Armenian Premier League",
"Alashkert": "Armenian Premier League",
"Ararat Yerevan": "Armenian Premier League",
"Belenseses SAD": "Liga Portugal 2",
"Casa Pia AC": "Liga Portugal 2",
"CD Feirense": "Liga Portugal 2",
"Mouscron": "Belgian Pro League",
}
